sudo: required

language: cpp

compiler: gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7

jobs:
  include:
    - stage: "Build"
      name: "Build paste-light"
      script: make
      name: "Build and Install paste-light"
      script: make && sudo make install
    - stage: "Test"
      name: "Build paste-light tests"
      script: make tests
      name: "Run paste-light tests"
      script: cd tests && ./test_paste_light
