#!/usr/bin/env bash

EXEC_INIT=false
EXEC_ADD=false
EXEC_COMP=false

function isInit() {
  if [[ -f .paste ]]; then
    return 0
  else
    return 1
  fi
}

function isOtherArgs() {
  # Add Arguments that the user can execute
  local poss_exec=( "$EXEC_INIT" "$EXEC_ADD" "$EXEC_COMP" )
  for i in "${poss_exec[@]}"; do
    if [[ $i = true ]]; then
      count=$(expr $count + 1)
    fi
  done

  if [[ $count -gt 1 ]]; then
    return 0
  else
    return 1
  fi
}

function initialize() {
  if isOtherArgs; then echo You cannot execute initialize command with other arguments. See --help. && exit 1; else
    if isInit; then echo Project already initialized && exit 0; else
      mkdir posts && touch .paste
      echo -e 'Project initialized\nSee --help for usage.'
      exit 0
    fi
  fi
}

function addPost() {
  if isOtherArgs; then echo You cannot add a new post with other commands. See --help. && exit 1; else
    if isInit; then
      touch posts/$POST_FILE
      if [ -z $EDITOR ]; then
        nano posts/$POST_FILE
      else
        $EDITOR posts/$POST_FILE
      fi
      exit 0
    fi
  fi
}

function genIndex() {
  if isOtherArgs; then echo You cannot execute compile command with other arguments. See --help. && exit 1; else
    if isInit; then
			mkdir -p build
      local postCount=$(find ./posts -maxdepth 1 -type f | wc -l)
			if [ -f test.html ]; then rm test.html && touch test.html; else touch test.html; fi
			genHeader test.html
			for (( i=1; i<=$postCount; i++ )); do
				local fileName=$(find ./posts -type f | awk NR==$i)
				# Build Files without comments and HTML format
				cat $fileName | sed -e '/^\s*{{*.*$/d' > build/$(echo $fileName | sed 's/.\/posts\///g').paste

				# Generate Table Rows
				echo "<tr class=\"paste-tbl-row\">" >> test.html
				genRow test.html "$(getPostName $i)"
				genRow test.html "$(getDate $i)"
				genRow test.html "$(getFileType $i)"
				genRow test.html "<a href="build/$(echo $fileName | sed 's/.\/posts\///g').paste">get</a>"
				echo "</tr>" >> test.html
			done
			printf '%s\n%s' '</table>' '</html>' >> test.html
    else
      echo This project is not initialized
    fi
  fi
}

function isPostName() {
	if cat $(find ./posts -type f | awk NR==$1) | sed -e 's/{{\*//g' -e 2q | grep 'title:' > /dev/null 2>&1; then
		return 0
	else
		return 1
	fi
}

function getPostName() {
	if isPostName $i; then
		cat $(find ./posts -type f | awk NR==$i) | sed -e 's/{{\*//g' -e 2q | grep 'title:' | cut -d : -f2 | sed -e's/^[ \t]*//'
	else
		echo -e 'Title not found for' $(find ./posts -type f | awk NR==$i) '\nPlease add a title' && exit 1
	fi
}

function isDate() {
	if cat $(find ./posts -type f | awk NR==$1) | sed -e 's/{{\*//g' -e 2q | grep 'date:' > /dev/null 2>&1; then
		return 0
	else
		return 1
	fi
}

function getDate() {
	if isDate $1; then
		cat $(find ./posts -type f | awk NR==$i) | sed -e 's/{{\*//g' -e 2q | grep 'date:' | cut -d : -f2 | sed -e 's/^[ \t]*//'
	fi
}

function getFileType() {
	echo $(find ./posts -type f | awk NR==$1 | sed 's/.\/posts\///g' | cut -d . -f2)
}

function genHeader() {
	printf '%s\n%s\n%s\n%s' '<html>' '<header>' '<link rel="stylesheet" type="text/css" href="style.css">' '</header>' > $1
	printf '\n%s\n%s\n' '<table id="paste-tbl-container">' '<tr class="paste-tbl-row">' >> $1
	printf  '%s\n%s\n%s\n%s\n%s\n' '<th class="paste-tbl-header">Name</th>' '<th class="paste-tbl-header">Date</th>' '<th class="paste-tbl-header">Filetype</th>' '<th class="paste-tbl-header">Get</th>' '</tr>' >> $1
}

function genRow() {
	printf '%s\n' "<td class=\"paste-tbl-data\">$2</td>" >> $1
}

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"
case $key in
  -init|--initialize)
  EXEC_INIT=true
  shift
  ;;
  -a|--add)
  if [[ $2 = "" ]] || [[ $2 =~ ^- ]]; then
    echo add takes one arguement. See --help && exit 1
  else
    POST_FILE="$2"
    EXEC_ADD=true
  fi
  shift
  ;;
  -c|--compile)
  EXEC_COMP=true
  shift
  ;;
  *)
  POSITIONAL+=("$1")
  shift
  ;;
esac
done
set -- "${POSITIONAL[@]}"

if [[ $EXEC_INIT = true ]]; then initialize; fi
if [[ $EXEC_ADD = true ]]; then addPost; fi
if [[ $EXEC_COMP = true ]]; then genIndex; fi
