void html_generate_tag(std::ostream&, std::string);
void html_generate_tag(std::ostream&, std::string, std::string);
void html_generate_tag_class(std::ostream&, std::string, std::string, std::string);
void html_generate_tag_id(std::ostream&, std::string, std::string, std::string);
void html_generate_tag_start(std::ostream&, std::string);
void html_generate_tag_start_class(std::ostream&, std::string, std::string);
void html_generate_tag_start_id(std::ostream&, std::string, std::string);
void html_generate_tag_end(std::ostream&, std::string);
void html_generate_footer(std::ostream&);
void html_generate_link(std::ostream&);
void html_generate_script(std::ostream&);
void html_generate_title(std::ostream&);
